name: crop_image
description: An image cropper widget, with 90-degree rotations. Supports mobile, web and desktop.
version: 1.0.5
homepage: https://github.com/deakjahn/crop_image

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  meta: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:
