name: crop_image
description: An image cropper widget, with 90-degree rotations. Supports mobile, web and desktop.
version: 1.0.7
homepage: https://github.com/deakjahn/crop_image

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  meta: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:
