name: crop_image
description: An image cropper widget. Supports mobile, web and desktop.
version: 1.0.1
homepage: https://github.com/deakjahn/crop_image

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  meta: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
